# Generated by Django 4.0.3 on 2022-03-27 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizName', models.CharField(max_length=128, null=True, unique=True)),
                ('quizSubject', models.CharField(max_length=128, null=True)),
                ('quizDifficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], default=('easy', 'Easy'), max_length=10)),
                ('scoreToPass', models.IntegerField(default=0)),
                ('numOfQue', models.IntegerField(default=1)),
                ('slug', models.SlugField(unique=True)),
                ('likes', models.ManyToManyField(related_name='quiz_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'quizzes',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='media/profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User',
            },
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquizitive.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'scores',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(max_length=500, unique=True)),
                ('questionMarks', models.IntegerField(default=1)),
                ('optiona', models.CharField(max_length=500, null=True)),
                ('optionb', models.CharField(max_length=500, null=True)),
                ('optionc', models.CharField(max_length=500, null=True)),
                ('optiond', models.CharField(max_length=500, null=True)),
                ('correctAnswer', models.CharField(max_length=500)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='inquizitive.quiz')),
            ],
            options={
                'verbose_name_plural': 'questions',
            },
        ),
    ]
