# Generated by Django 2.2.26 on 2022-03-07 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquizitive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='creator',
        ),
    ]
