# Generated by Django 4.0.3 on 2022-03-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquizitive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quizName',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
