# Generated by Django 4.0.3 on 2022-03-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquizitive', '0002_alter_quiz_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
