# Generated by Django 3.2.3 on 2022-03-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquizitive', '0002_alter_quiz_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile',
            new_name='profile_pic',
        ),
    ]
