# Generated by Django 4.0.3 on 2022-03-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquizitive', '0002_alter_quiz_quizname'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
