# Generated by Django 4.0.3 on 2022-03-08 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquizitive', '0003_auto_20220307_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='quiz',
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.JSONField(default='anythingg'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='creator',
            field=models.ForeignKey(default='default value', on_delete=django.db.models.deletion.CASCADE, to='inquizitive.userprofile'),
        ),
    ]
