# Generated by Django 4.0.3 on 2022-03-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquizitive', '0004_alter_quiz_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='optiond',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
