# Generated by Django 4.0.3 on 2022-03-23 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquizitive', '0004_remove_quiz_likes_quiz_likes_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
