# Generated by Django 3.2.3 on 2022-03-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquizitive', '0005_alter_userprofile_profile_pic'),
        ('inquizitive', '0005_delete_like'),
    ]

    operations = [
    ]
