# Generated by Django 3.2.3 on 2022-03-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquizitive', '0005_question_optiond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(default='default.jpg', upload_to='profile_images'),
        ),
    ]
