# Generated by Django 4.0.3 on 2022-03-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquizitive', '0005_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correctAnswer',
            field=models.CharField(max_length=500, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='optiona',
            field=models.CharField(max_length=500, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='optionb',
            field=models.CharField(max_length=500, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='optionc',
            field=models.CharField(max_length=500, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='optiond',
            field=models.CharField(max_length=500, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionMarks',
            field=models.IntegerField(default=1, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionText',
            field=models.CharField(max_length=500, unique=True, verbose_name=''),
        ),
    ]
