# Generated by Django 4.0.3 on 2022-03-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquizitive', '0007_quiz_passcode_alter_question_correctanswer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='passcode',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
