# Generated by Django 4.0.3 on 2022-03-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquizitive', '0010_alter_quiz_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionText',
            field=models.CharField(max_length=500),
        ),
    ]
