# Generated by Django 3.2.3 on 2022-03-24 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquizitive', '0008_alter_userprofile_profile_pic'),
        ('inquizitive', '0011_alter_question_questiontext'),
    ]

    operations = [
    ]
